\pagenumbering{arabic}

\mainmatter

# Introduction

In recent years, numerous green building certification schemes have been developed, "aimed at mitigating the impact of buildings on the natural environment through sustainable design" [@Vierra2016]. The impact of buildings on the environment is huge; for instance, "US buildings alone are responsible for more CO~2~ emissions than any other entire country in the world except China" [@Kats2003]. Many of these certifications focus on rating the sustainability and energy efficiency of buildings.

This drive towards sustainable design started in the 1990s with the Building Research Establishment (BRE) Environmental Assessment Method (BREEAM), and was followed in 2000 by the US Leadership in Energy and Environmental Design (LEED) rating system [@Vierra2016]. This drive for environmental sustainability in products and buildings has accelerated in recent years due to growing concerns about environmental issues. 

Certifications encourage the construction of green buildings by reducing information asymmetries associated with green buildings, which cause potential buyers to not fully price in the benefits of green technology [@Matisoff2016]. While green features provide tangible and intangible benefits such as lower electricity bills and better environment, these features are unobservable at the demand side before purchase. Some of these features such as material sourcing might not even be observable after purchase. This problem is similar to the "market for lemons" problem [@Akerlof1970], where potential buyers cannot differentiate between the presence and absence of green features. As a result, there is a pooling equilibrium where potential buyers/tenants are not willing to fully price in the green features which landlords or developers claim to exist. Assuming green features require additional costs to build in, the lack of price premiums means that building in green features leads to lower profits. Developers and constructors will choose not to build in green features to their buildings because the additional costs are not covered by a corresponding price premium.

A credible certification can verify these unobservable green characteristics, increasing confidence in the validity of the environmental information provided, and hence act as a signal to potential buyers about the green features and quality of the building. This would justify a price premium for green features, which would in turn pay for the additional costs required to build in green features, increasing the construction of these environmentally sustainable buildings.

Some literature have shown that the costs of building green features are actually not that high, implying that developers should not require large incentives to build in green features. These studies have demonstrated that the average cost premium for green buildings are only about 1% to 2% [see @Bartlett2000; also @Kats2003]. The Building and Construction Authority of Singapore (BCA) conducted a study in 2008 and found a cost premium of between 0.3% to 8% for their Green Mark certification, depending on the level of certification desired.

Regardless, even if the cost premiums are low, these cost premiums still need to be offset by a corresponding price premium. Buyers and tenants are unwilling to pay for green features not because they do not value green features, but because they cannot observe them before the purchase or rental agreement. A certification acts as a signal or assurance of quality, to allow potential tenants and buyers to fully price in the benefits from the green features.

## Green Mark (GM) Certification in Singapore

The Green Mark scheme was launched in January 2005 by the BCA to encourage the construction of more environmentally friendly and energy efficient buildings. The GM scheme rates and certifies buildings according to five main criteria: energy efficiency, water efficiency, environmental protection, indoor environmental quality, and other green and innovative features [@BCAAssessment].

Buildings which apply for the GM certification would be assessed on the criteria listed above, and would be scored on a points basis. These scores would then be converted to an award type (Certified, Gold, Gold Plus, Platinum). 

In order to further encourage developers to incorporate Green Building Technologies (GBTs) into their developments, the BCA set aside $20 million on the Green Mark Incentive Scheme (GMIS) in 2006. This was a scheme aimed at accelerating the adoption of green technologies, by providing cash incentives to developers, building owners, architects and mechanical and electrical (M&E) engineers who "[made] efforts to achieve at least a BCA Green Mark Gold rating or higher". The cash incentives would be split into two stages: half of which would be disbursed upon successful certification during the design or construction stage, and the remaining would be disbursed after validation, one year after the Temporary Occupation Permit (TOP) date. [@BCAGMIS]

## Aim of Study

The aim of this paper is to explore the intangible effects of an environmental certification or award, using data from housing transactions in Singapore. 

This study uses a difference-in-differences (DID) approach to separate the intangible effects of the GM award from the tangible effects of it (energy savings), through its effect on housing transaction prices. 

The intangible effects of environmental certifications are important because these certifications are meant to incentivise certain behaviour, in this case, constructing energy efficient buildings. In order for certifications to incentivise private companies to adopt certain practices, they need to provide a price premium to offset the cost premium associated with "good behaviour". This price premium generated must be on top of the premium that buyers attach to the developers' claims about the energy performance of the property.

\newpage