
# Literature Review

Even before the proliferation of green certification schemes, some early papers in the 1980s have already demonstrated the relationship between energy efficiency and residential property prices [see @Johnson1983; @Laquatra1986; @Dinan1989]. These papers demonstrate that improvements in energy efficiency, which lead to cost savings, are capitalised in the housing market. Cost savings from energy efficient investments are translated into increased housing prices. 

More recently, the growing concern about climate change (and the proliferation of green certifications) has sparked more research on the effect of green certifications on housing prices. These studies show that green labelling or certification has a positive effect on residential property prices.

Using a hedonic pricing model, Jayantha and Man [-@Jayantha2013] studied two green certifications in Hong Kong, namely the Hong Kong Building Environmental Assessment Method (HK-BEAM) and the Hong Kong Green Building Council (HK-GBC) award. Using data from 1 July 2003 to 1 September 2008 (to avoid the SARS outbreak in 2003 and the global financial crisis in 2008), the study found that people were willing to pay between 3.4 and 6.4 percent more for green certified buildings. 

Several studies also used used hedonic price models to analyse the LEED programme in the US. For instance, Bond and Devine [-@Bond2016] used a hedonic model with property-level characteristics such as presence of gym or swimming pool, as well as unit-level characteristics like the size of a dwelling unit, to model housing prices. The study also used coarsened exact matching (CEM) to balance the control (non-certified) and treatment (certified) groups. The motivation behind this is similar to propensity score matching; that is to find suitable controls for each treatment observation. The results from this study indicate that non-certified properties that are marketed as having green features do command a price premium over other non-certified properties, and certification adds a 4 percent premium on top of this, demonstrating the effect of the certification signal.

Another study by Kahn and Kok [-@Kahn2014] analysed various certifications like Energy Star, LEED and GreenPoint in the California housing market. The study used transactions of all single-family home sales in California from 2007 to 2012 and found a premium of about 5% for certified homes. The study also found variations in the premium based on environmental ideology and local climatic conditions (e.g. hotter areas demand more cooling and hence higher importance of energy efficiency). 

Although many studies focus on the US market, there are a few studies that have attempted to examine if the same price premium holds in other markets around the world. Fuerst and Shimizu [-@Fuerst2016a] analysed the Japanese housing market and found a 5% higher asking price for Tokyo Green Label certified condominiums compared to uncertified condominiums. The study also specifically tested if sellers overestimate the value of the green label by testing if transaction prices of green labelled buildings differed from their average asking prices, and found no evidence of such phenomena. This provides some evidence that the price premium is not unique to the US market, and can be generalised to other countries.

Deng, Li, and Quigley [-@Deng2012] studied the GM program in Singapore using a two-stage hedonic regression model, and found a four percent premium for GM-rated dwellings. In this approach, the first stage regression was to model price as a function of hedonic characteristics, year and month fixed effects, and project-level fixed effects. The project-level fixed effects were then regressed on the project-level characteristics in the second stage regression to obtain the marginal willingness to pay (WTP) for the project-level characteristics, including the GM award.

Heinzle, Yip and Xing [-@Heinzle2013] also studied the GM program using a stated preference study and found a price premium between 3.78 and 7.98 percent, depending on the level of certification (e.g. Gold, Platinum). This study also looked at the importance of various housing attributes in determining the purchase decisions of a potential buyer. The study found that price, size, location (Core Central Region/Rest of Central Region/Outside Central Region), the direction or facing of the living room and distance to MRT are the most important attributes (in that order). Apart from price which is the dependent variable in the hedonic model and facing of the living room which is unavailable, the rest of these variables are included in some form or other (e.g. location is absorbed by the 4 digit postal code fixed effects in the hedonic model).

A few studies pointed out the heterogeneous incentives to invest in energy efficiency between owner-occupiers and landlords. Michelsen, Mense, and Kholodilin [-@Michelsen2015] studied the Berlin apartment housing market and found that the implicit price of energy efficiency in a tenant-occupied dwelling is less than that of an owner-occupied one, by a factor of 2.5. They also explain that this is due to tenants not having enough technical understanding to evaluate the true quality of a dwelling, and that they also apply larger discount rates to future energy savings or energy price increases. 

Even though there are plenty of studies that show that green labelled properties command a price premium over non-labelled ones, most of these studies, as Brounen and Kok [-@Brounen2011] pointed out in their study, are unable to distinguish between the intangible effects of labelling itself and the economic effects of energy savings. This is because most of these studies use a simple hedonic pricing approach without attempting to control for the energy savings, or using a DID or fixed effects approach. These studies are also vulnerable to omitted variable bias, since it is quite likely that green labelled properties are of higher quality. One of the reasons this is so is because many "green" features also have positive non-environmental effects; for instance "double-glazing reduces noise pollution and increases security" [@Fuerst2016]. As a result, the certification dummy in these hedonic models is also capturing unobserved quality differences between labelled and non-labelled properties, overestimating the effect of labelling or certification. 

A few studies try to get around the problem of being unable to distinguish between the intangible effects of labelling and tangible effects of energy saving, but are still unable to separate the effect from unobserved quality differences between labelled and non-labelled properties. The study by Kahn and Kok [-@Kahn2014] used a proxy for ideology to partially separate the effects of the energy savings from the intangible labelling effects. Another study uses information on building-level energy usage to separate the effects of energy savings from the intangible effects of labelling [@Fuerst2016b].

It is also important to note that while green certifications do contribute a price premium to properties, the price premium has been found to decrease as the supply of certified properties increase, indicating the presence of general equilibrium effects [@Chegut2014].

This study will use a DID approach to separate the intangible labelling effects from the energy saving effects, and also to avoid the omitted variable bias problem. This should be a cleaner approach than using proxies, but also relies on a (reasonable) assumption that energy saving features of a property would be marketed to property buyers regardless of whether a property is (or going to be) GM-rated.

\newpage