
# Conclusion

The main objective of this study was to investigate the intangible effects of green labelling on residential housing prices. A large percentage of previous studies on green labelling or certifications did not try to separate the economic effects of energy savings from the intangible effects of labelling, bundling these effects together. A few studies attempted to separate these effects using proxies for environmental ideology or data on energy usage to separate these effects; this study uses a DID approach instead.

The empirical results suggest that GM-rated dwellings are higher quality in general, and that the intangible effects of labelling contribute a `r extract_coef(did_with_conquas_cat, "award_after")` price premium in the private residential market in Singapore.

These results corroborate previous studies' findings that green certification is a good selling point for developers, since they provide a price premium on top of the economic effects of energy savings. This should encourage more property developers to integrate sustainable designs into their projects, thereby helping to reduce the environmental impact from building construction.

One important implication is that green certification can be a viable strategy for governments seeking to promote sustainable development. The findings in this study show that the the housing market values the certification on top of information on energy savings, which is the main assumption behind the use of certification to promote sustainable development.

One of the limitations of this study is that it does not distinguish between the various intangible effects that a certification might have. Firstly, the GM certification could raise awareness about sustainable construction amongst home buyers and hence increase the demand for green properties, resulting in the observed price premium. Secondly, the award provides confidence and verification about developers' claims about the energy efficiency of the development and increase home buyers' willingness to pay for the energy efficient or green features. Thirdly, it could simply signal quality that could be unrelated to green features; home buyers might feel that if a property can receive a certification, then it cannot be too bad. The intangible effects are likely to be a combination of these effects (and some others not stated), but if home buyers do not actually care about the green features as they do about using the certification as an assurance of general quality, the use of certifications to increase sustainable development will be limited since it does not increase the demand for energy efficient features. There is some evidence that the intrinsic meaning of certifications does not matter as much as having a certification (see @DeMagistris2015), so it could well be possible that the price premium that is found on GM-rated properties is mainly due to the certification providing an assurance of general quality instead of assurance of sustainable development.

Another limitation of this study is that the use of the date of the BCA awards night as the date of GM award makes it challenging to check the common trend assumption required for the DID methodology. This study fails to empirically confirm that GM-rated and non-GM rated properties are indeed comparable (i.e. their prices trend together), though I cannot think of a reason why they would not be.

While the scope of this study is limited (green certification in Singapore housing market), further research could be done to explore if these intangible labelling effects are valid outside of the Singapore housing market, or even if they hold for other types of certifications. Such studies can evaluate the viability of using certifications to encourage or incentivise "good behaviour".

\newpage
